init:
  - pwsh: |
       $env:var1 = "1"
       Write-host "var1: $env:var1"

install:
  - pwsh: |
      Write-host "var1: $env:var1"
      if ("1" -eq $env:var1)
      {
        Write-host "hello"
      }
