image: Visual Studio 2017
environment:
  apiKey:
    secure: mD9BJbJ4vx3zjm7jf8OP6w==
build:
  verbosity: minimal
after_build:
- cmd: '\TestVariables\bin\Debug\netcoreapp2.2\dotnet TestVariables.dll'
