image: 
- Visual Studio 2017
- Ubuntu
environment:
  apiKey:
    secure: mD9BJbJ4vx3zjm7jf8OP6w==
build:
  verbosity: quiet
before_build:
- nuget restore -verbosity quiet
after_build:
- cmd: dotnet TestVariables\bin\Debug\netcoreapp2.2\TestVariables.dll
- sh:  dotnet ./TestVariables/bin/Debug/netcoreapp2.2/TestVariables.dll
