version: 1.0.{build}
image: Windows Server 2019
environment:
  APPVEYOR_RDP_PASSWORD: iis6!dfu1234
services: postgresql101
install:
- ps: |
    if ((Invoke-WebRequest https://api.ipify.org).content -ne "13.83.108.89") {throw}
    Install-Product node 8
    Get-Service | ? {$_.name -like "post*"}
build: off
