init:
  - pwsh: |
       $global:var1 = "1"
       Write-host "var1: $global:var1"

install:
  - pwsh: |
      Write-host "var1: $global:var1"
      if ("1" -eq $global:var1)
      {
        Write-host "hello"
      }

build: off
