image: Visual Studio 2017
environment:
  apiKey:
    secure: mD9BJbJ4vx3zjm7jf8OP6w==
build:
  verbosity: quiet
before_build:
- nuget restore -verbosity quiet
after_build:
- cd estVariables\bin\Debug\netcoreapp2.2
- dotnet TestVariables\bin\Debug\netcoreapp2.2\TestVariables.dll
