environment:  
  matrix:
  - {}
  - {}
  - {}
  - {}
  - {}
  - {}
  - {}
  - {}
  - {}
  - {}
install:
- ps: fsutil file createnew testfile 300000000
build: off
test: off
artifacts:
- path: testfile
